<a href="https://colab.research.google.com/github/Ansh3931up/DS-Course_Notes/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas: It is a fast ,powerful, flexible and easy to use open source data analysis and manipulation built on top of the python programming languagae

In [159]:
import pandas as pd
pd.read_csv("/content/industry.csv")

                         Industry
0              Accounting/Finance
1    Advertising/Public Relations
2              Aerospace/Aviation
3   Arts/Entertainment/Publishing
4                      Automotive
5                Banking/Mortgage
6            Business Development
7            Business Opportunity
8         Clerical/Administrative
9         Construction/Facilities
10                 Consumer Goods
11               Customer Service
12             Education/Training
13               Energy/Utilities
14                    Engineering
15            Government/Military
16                          Green
17                     Healthcare
18             Hospitality/Travel
19                Human Resources
20       Installation/Maintenance
21                      Insurance
22                       Internet
23                Job Search Aids
24       Law Enforcement/Security
25                          Legal
26           Management/Executive
27       Manufacturing/Operations
28                      Marketing
29           Non-Profit/Volunteer
30         Pharmaceutical/Biotech
31          Professional Services
32             QA/Quality Control
33                    Real Estate
34        Restaurant/Food Service
35                         Retail
36                          Sales
37               Science/Research
38                  Skilled Labor
39                     Technology
40             Telecommunications
41       Transportation/Logistics
42                          Other

In [160]:
pd.read_csv("/content/industry.csv",header=None)

                                0
0                        Industry
1              Accounting/Finance
2    Advertising/Public Relations
3              Aerospace/Aviation
4   Arts/Entertainment/Publishing
5                      Automotive
6                Banking/Mortgage
7            Business Development
8            Business Opportunity
9         Clerical/Administrative
10        Construction/Facilities
11                 Consumer Goods
12               Customer Service
13             Education/Training
14               Energy/Utilities
15                    Engineering
16            Government/Military
17                          Green
18                     Healthcare
19             Hospitality/Travel
20                Human Resources
21       Installation/Maintenance
22                      Insurance
23                       Internet
24                Job Search Aids
25       Law Enforcement/Security
26                          Legal
27           Management/Executive
28       Manufacturing/Operations
29                      Marketing
30           Non-Profit/Volunteer
31         Pharmaceutical/Biotech
32          Professional Services
33             QA/Quality Control
34                    Real Estate
35        Restaurant/Food Service
36                         Retail
37                          Sales
38               Science/Research
39                  Skilled Labor
40                     Technology
41             Telecommunications
42       Transportation/Logistics
43                          Other

In [161]:
pd.read_csv("/content/industry.csv",skiprows=2)

     Advertising/Public Relations
0              Aerospace/Aviation
1   Arts/Entertainment/Publishing
2                      Automotive
3                Banking/Mortgage
4            Business Development
5            Business Opportunity
6         Clerical/Administrative
7         Construction/Facilities
8                  Consumer Goods
9                Customer Service
10             Education/Training
11               Energy/Utilities
12                    Engineering
13            Government/Military
14                          Green
15                     Healthcare
16             Hospitality/Travel
17                Human Resources
18       Installation/Maintenance
19                      Insurance
20                       Internet
21                Job Search Aids
22       Law Enforcement/Security
23                          Legal
24           Management/Executive
25       Manufacturing/Operations
26                      Marketing
27           Non-Profit/Volunteer
28         Pharmaceutical/Biotech
29          Professional Services
30             QA/Quality Control
31                    Real Estate
32        Restaurant/Food Service
33                         Retail
34                          Sales
35               Science/Research
36                  Skilled Labor
37                     Technology
38             Telecommunications
39       Transportation/Logistics
40                          Other

In [162]:
df=pd.read_csv("/content/industry.csv",usecols=[])

In [163]:
type(df)

pandas.core.frame.DataFrame

In [164]:
# type(df[""])

In [165]:
l=[1,2,3,4]
s=pd.Series(l)
s

0    1
1    2
2    3
3    4
dtype: int64

In [166]:
s[0]

1

In [167]:
s[1:]

1    2
2    3
3    4
dtype: int64

In [168]:
d=pd.Series([100,200,300],index=["a","b","c"])
d

a    100
b    200
c    300
dtype: int64

In [169]:
type(d)

pandas.core.series.Series

In [170]:
d.index

Index(['a', 'b', 'c'], dtype='object')

In [171]:
d.reset_index(drop=True)

0    100
1    200
2    300
dtype: int64

In [172]:
pd.DataFrame(d)

     0
a  100
b  200
c  300

In [173]:
d.head(1)

a    100
dtype: int64

In [174]:
d.tail(1)

c    300
dtype: int64

In [175]:
d.shape

(3,)

In [176]:
d.sample()

c    300
dtype: int64

In [177]:
d.info()

<class 'pandas.core.series.Series'>
Index: 3 entries, a to c
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 156.0+ bytes

In [178]:
d.dtypes

dtype('int64')

In [179]:
s=pd.Series([2,3,4],index=[100,"ask",300])
d=pd.DataFrame(s)
d

     0
100  2
ask  3
300  4

In [180]:
d["new column"]="ansh"
d

     0 new column
100  2       ansh
ask  3       ansh
300  4       ansh

In [181]:
d["new columns"]=[1,2,3]
d

     0 new column  new columns
100  2       ansh            1
ask  3       ansh            2
300  4       ansh            3

In [182]:
d.reset_index()
d

     0 new column  new columns
100  2       ansh            1
ask  3       ansh            2
300  4       ansh            3

In [183]:
# d[["col1","col2"]]

In [184]:
# pd.read_excel("")

In [185]:
# pd.read_html("")

In [186]:
pip install lxml

Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (4.9.4)

In [187]:
d.to_csv("players.csv",index=False)

In [188]:
import requests

In [189]:
data=requests.get("https://api.github.com/repos/pandas-dev/pandas/issues")
data

In [190]:
data.json()

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60003',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60003/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60003/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60003/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/60003',
  'id': 2572779091,
  'node_id': 'I_kwDOAA0YD86ZWX5T',
  'number': 60003,
  'title': 'TYP: More precise NaT stubs',
  'user': {'login': 'randolf-scholz',
   'id': 39696536,
   'node_id': 'MDQ6VXNlcjM5Njk2NTM2',
   'avatar_url': 'https://avatars.githubusercontent.com/u/39696536?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/randolf-scholz',
   'html_url': 'https://github.com/randolf-scholz',
   'followers_url': 'https://api.github.com/users/randolf-scholz/followers',
   'following_url': 'https://api.github.com/users/randolf-scholz/following{/other_user}',
   'gists_url': 'https://api.github.com/users/randolf-scholz/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/randolf-scholz/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/randolf-scholz/subscriptions',
   'organizations_url': 'https://api.github.com/users/randolf-scholz/orgs',
   'repos_url': 'https://api.github.com/users/randolf-scholz/repos',
   'events_url': 'https://api.github.com/users/randolf-scholz/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/randolf-scholz/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76812,
    'node_id': 'MDU6TGFiZWw3NjgxMg==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement',
    'name': 'Enhancement',
    'color': '4E9A06',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-10-08T10:30:01Z',
  'updated_at': '2024-10-08T10:30:01Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'body': '### Feature Type\n\n- [ ] Adding new functionality to pandas\n\n- [X] Changing existing functionality in pandas\n\n- [ ] Removing existing functionality in pandas\n\n\n### Problem Description\n\nAmendment to #59996. The current stub has some imprecise typing.\r\n\n\n### Feature Description\n\n- inequalities do not cover comparisons of NaTType with itself.\r\n- addition/subtraction does not cover `pd.Period` and numpy types.\r\n- dunder methods should be marked with positional-only parameters, even if the class supports keyword usage.\n\n### Alternative Solutions\n\nN/A\n\n### Additional Context\n\n_No response_',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60003/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60003/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60002',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60002/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60002/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60002/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/60002',
  'id': 2572484029,
  'node_id': 'PR_kwDOAA0YD8596lP7',
  'number': 60002,
  'title': 'Typing: More precise NaT stub',
  'user': {'login': 'randolf-scholz',
   'id': 39696536,
   'node_id': 'MDQ6VXNlcjM5Njk2NTM2',
   'avatar_url': 'https://avatars.githubusercontent.com/u/39696536?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/randolf-scholz',
   'html_url': 'https://github.com/randolf-scholz',
   'followers_url': 'https://api.github.com/users/randolf-scholz/followers',
   'following_url': 'https://api.github.com/users/randolf-scholz/following{/other_user}',
   'gists_url': 'https://api.github.com/users/randolf-scholz/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/randolf-scholz/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/randolf-scholz/subscriptions',
   'organizations_url': 'https://api.github.com/users/randolf-scholz/orgs',
   'repos_url': 'https://api.github.com/users/randolf-scholz/repos',
   'events_url': 'https://api.github.com/users/randolf-scholz/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/randolf-scholz/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-10-08T08:32:21Z',
  'updated_at': '2024-10-08T10:30:25Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60002',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/60002',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/60002.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/60002.patch',
   'merged_at': None},
  'body': '- marked arguments in dunder methods positional only\r\n  (important for subclassing and protocols)\r\n- added `Period`, `np.datetime64` and `np.timedelta64` as compatible for `__add__` and `__sub__`\r\n- added `np.datetime64` and `np.timedelta64`  as compatible with `__floordiv__` and `__truediv__`\r\n- reworked comparisons:\r\n  - removed protocol and use plain definition\r\n  - changed return type from `bool` to `Literal[False]`\r\n  - added `Self` to comparable types, so that `pd.NaT > pd.NaT` is considered valid\r\n\r\n\r\n- [x] closes #60003 (Replace xxxx with the GitHub issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n\r\n\r\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60002/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60002/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60001',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60001/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60001/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60001/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/60001',
  'id': 2572364169,
  'node_id': 'PR_kwDOAA0YD8596NKe',
  'number': 60001,
  'title': 'Fix Styler docstring',
  'user': {'login': 'albertvillanova',
   'id': 8515462,
   'node_id': 'MDQ6VXNlcjg1MTU0NjI=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8515462?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/albertvillanova',
   'html_url': 'https://github.com/albertvillanova',
   'followers_url': 'https://api.github.com/users/albertvillanova/followers',
   'following_url': 'https://api.github.com/users/albertvillanova/following{/other_user}',
   'gists_url': 'https://api.github.com/users/albertvillanova/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/albertvillanova/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/albertvillanova/subscriptions',
   'organizations_url': 'https://api.github.com/users/albertvillanova/orgs',
   'repos_url': 'https://api.github.com/users/albertvillanova/repos',
   'events_url': 'https://api.github.com/users/albertvillanova/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/albertvillanova/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-10-08T07:41:09Z',
  'updated_at': '2024-10-08T08:31:21Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60001',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/60001',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/60001.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/60001.patch',
   'merged_at': None},
  'body': '- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60001/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60001/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59998',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59998/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59998/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59998/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/59998',
  'id': 2570929321,
  'node_id': 'PR_kwDOAA0YD85914lo',
  'number': 59998,
  'title': '[pre-commit.ci] pre-commit autoupdate',
  'user': {'login': 'pre-commit-ci[bot]',
   'id': 66853113,
   'node_id': 'MDM6Qm90NjY4NTMxMTM=',
   'avatar_url': 'https://avatars.githubusercontent.com/in/68672?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/pre-commit-ci%5Bbot%5D',
   'html_url': 'https://github.com/apps/pre-commit-ci',
   'followers_url': 'https://api.github.com/users/pre-commit-ci%5Bbot%5D/followers',
   'following_url': 'https://api.github.com/users/pre-commit-ci%5Bbot%5D/following{/other_user}',
   'gists_url': 'https://api.github.com/users/pre-commit-ci%5Bbot%5D/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/pre-commit-ci%5Bbot%5D/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/pre-commit-ci%5Bbot%5D/subscriptions',
   'organizations_url': 'https://api.github.com/users/pre-commit-ci%5Bbot%5D/orgs',
   'repos_url': 'https://api.github.com/users/pre-commit-ci%5Bbot%5D/repos',
   'events_url': 'https://api.github.com/users/pre-commit-ci%5Bbot%5D/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/pre-commit-ci%5Bbot%5D/received_events',
   'type': 'Bot',
   'site_admin': False},
  'labels': [{'id': 106935113,
    'node_id': 'MDU6TGFiZWwxMDY5MzUxMTM=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Code%20Style',
    'name': 'Code Style',
    'color': 'eb6420',
    'default': False,
    'description': 'Code style, linting, code_checks'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/102',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/102',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/102/labels',
   'id': 9021906,
   'node_id': 'MI_kwDOAA0YD84AianS',
   'number': 102,
   'title': '3.0',
   'description': '',
   'creator': {'login': 'jbrockmendel',
    'id': 8078968,
    'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
    'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/jbrockmendel',
    'html_url': 'https://github.com/jbrockmendel',
    'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
    'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
    'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
    'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
    'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
    'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
    'type': 'User',
    'site_admin': False},
   'open_issues': 42,
   'closed_issues': 1325,
   'state': 'open',
   'created_at': '2023-02-08T18:16:49Z',
   'updated_at': '2024-10-08T02:35:04Z',
   'due_on': None,
   'closed_at': None},
  'comments': 3,
  'created_at': '2024-10-07T16:32:52Z',
  'updated_at': '2024-10-07T22:46:28Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59998',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/59998',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/59998.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/59998.patch',
   'merged_at': None},
  'body': '<!--pre-commit.ci start-->\r\nupdates:\r\n- [github.com/astral-sh/ruff-pre-commit: v0.5.0 → v0.6.9](https://github.com/astral-sh/ruff-pre-commit/compare/v0.5.0...v0.6.9)\r\n- [github.com/jendrikseipp/vulture: v2.11 → v2.13](https://github.com/jendrikseipp/vulture/compare/v2.11...v2.13)\r\n- [github.com/pre-commit/pre-commit-hooks: v4.6.0 → v5.0.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.6.0...v5.0.0)\r\n- [github.com/sphinx-contrib/sphinx-lint: v0.9.1 → v1.0.0](https://github.com/sphinx-contrib/sphinx-lint/compare/v0.9.1...v1.0.0)\r\n- [github.com/pre-commit/mirrors-clang-format: v18.1.8 → v19.1.1](https://github.com/pre-commit/mirrors-clang-format/compare/v18.1.8...v19.1.1)\r\n<!--pre-commit.ci end-->\r\n\r\nNote: pyupgrade 3.17 needs to be coordinated with an upgrade in mypy & pyright',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59998/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59998/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59997',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59997/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59997/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59997/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/59997',
  'id': 2570805315,
  'node_id': 'PR_kwDOAA0YD8591fRr',
  'number': 59997,
  'title': "BUG: fix #59965 skipna=True operations don't skip NaN in FloatingArrays",
  'user': {'login': 'cooolheater',
   'id': 184128544,
   'node_id': 'U_kgDOCvmUIA',
   'avatar_url': 'https://avatars.githubusercontent.com/u/184128544?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/cooolheater',
   'html_url': 'https://github.com/cooolheater',
   'followers_url': 'https://api.github.com/users/cooolheater/followers',
   'following_url': 'https://api.github.com/users/cooolheater/following{/other_user}',
   'gists_url': 'https://api.github.com/users/cooolheater/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/cooolheater/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/cooolheater/subscriptions',
   'organizations_url': 'https://api.github.com/users/cooolheater/orgs',
   'repos_url': 'https://api.github.com/users/cooolheater/repos',
   'events_url': 'https://api.github.com/users/cooolheater/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/cooolheater/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2024-10-07T15:36:46Z',
  'updated_at': '2024-10-07T23:54:09Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59997',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/59997',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/59997.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/59997.patch',
   'merged_at': None},
  'body': '    - Issue: The skipna was not properly handled for BaseMaskedArray\r\n    - Fix: Added mask for NA values\r\n    - Test: Added test to series/test_reductions since the test uses\r\n\r\n- [X] closes #59965\r\n- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59997/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59997/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59994',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59994/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59994/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59994/events',

CLass 02 Advance

In [191]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [192]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [193]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [194]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [195]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [196]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [197]:
a=df.describe() # this provide the statisical information about the numericsl column
a

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [198]:
b=a.describe()# five point service >> min,25%,50%,75%,max offen asked in interview
b

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000
mean,478.044230,111.733804,113.268089,115.596327,112.703219,112.273456,192.323930
std,320.815971,314.871366,314.252344,242.905673,314.490828,314.659717,330.625663
min,1.000000,0.000000,0.836071,0.420000,0.000000,0.000000,0.000000
25%,248.890382,0.000000,1.750000,18.725374,0.000000,0.000000,12.818250
50%,446.000000,0.435215,2.654321,28.849559,0.761504,0.190797,31.602104
75%,724.125000,1.000000,3.000000,48.500000,2.827058,2.104543,165.352371
max,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000

In [199]:
#to get the subset of data
df[["PassengerId" ,"Survived", "Pclass"]]

     PassengerId  Survived  Pclass
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

[891 rows x 3 columns]

In [200]:
df.dtypes # tells the datatype of the data

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [201]:
df.dtypes=="object" #object is a string datatype and if that data is object return true else false

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [202]:
df.dtypes[df.dtypes=="object"].index # return those series value where the inside condition is true

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [203]:
# the string data
df[df.dtypes[df.dtypes=="object"].index]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [204]:
df[df.dtypes[df.dtypes=="object"].index].describe()

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [205]:
# more info about categorical data
df.describe(include="object")

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [206]:
df.describe(include="all") # provide all info the object and categorical data both

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [207]:
# unique and freq for numerical data
df.astype('object').describe()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891,891,891,891,891,714.0,891,891,891,891.00,204,889
unique,891,2,3,891,2,88.0,7,7,681,248.00,147,3
top,1,0,3,"Braund, Mr. Owen Harris",male,24.0,0,0,347082,8.05,B96 B98,S
freq,1,549,491,1,577,30.0,608,678,7,43.00,4,644

In [208]:
df.shape

(891, 12)

In [209]:
df[0:100]#[start-index : end-1-index : step-count]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S

In [210]:
df[0:100:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
50,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.0,0,0,2669,7.2292,NaN,C
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C
70,71,0,2,"Jenkin, Mr. Stephen Curnow",male,32.0,0,0,C.A. 33111,10.5000,NaN,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.0,0,0,348123,7.6500,F G73,S
80,81,0,3,"Waelens, Mr. Achille",male,22.0,0,0,345767,9.0000,NaN,S
85,86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.0,3,0,3101278,15.8500,NaN,S
90,91,0,3,"Christmann, Mr. Emil",male,29.0,0,0,343276,8.0500,NaN,S
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S

In [211]:
df["family"]=df["SibSp"]+df["Parch"] # dd family column having data of sibSp and parch where sib is siblings and parch aare parent children
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

In [212]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  family       891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB

In [213]:
pd.Categorical(df["Pclass"]) # different categories of pclass

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

In [214]:
pd.Categorical(df["Cabin"]) # different categories of cabin

[NaN, 'C85', NaN, 'C123', NaN, ..., NaN, 'B42', NaN, 'C148', NaN]
Length: 891
Categories (147, object): ['A10', 'A14', 'A16', 'A19', ..., 'F38', 'F4', 'G6', 'T']

In [215]:
df["Cabin"].unique() # get all the unique values of the cabin

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [216]:
df["Cabin"].nunique() # gets the number of unique value of the data

147

In [217]:
df["Sex"].value_counts() # provide the number of male and female in sex dataset ka columns ki number of count bta deta hai

Sex
male      577
female    314
Name: count, dtype: int64

In [218]:
df["Sex"].value_counts(normalize=True)*100 # provide the number on percentage basis

Sex
male      64.758698
female    35.241302
Name: proportion, dtype: float64

In [219]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'family'],
      dtype='object')

In [220]:
# Q. How many  passengers are less than 5 year old
df['Age'][df['Age']<5].describe() # my approach
df[df['Age']<5].shape # teacher approach
len(df[df['Age']<5]) # teacher approach2

40

In [221]:
#Q. Name of the children less than 5 year old
# df[df['Age']<5]['Name'] # my approach  same  as teacher approach
list(df[df['Age']<5]['Name'])

['Palsson, Master. Gosta Leonard',
 'Sandstrom, Miss. Marguerite Rut',
 'Rice, Master. Eugene',
 'Laroche, Miss. Simonne Marie Anne Andree',
 'Skoog, Master. Harald',
 'Caldwell, Master. Alden Gates',
 'Andersson, Miss. Ellis Anna Maria',
 'Panula, Master. Eino Viljami',
 'Rice, Master. Arthur',
 'Johnson, Miss. Eleanor Ileen',
 'Becker, Master. Richard F',
 'Kink-Heilmann, Miss. Luise Gretchen',
 'Navratil, Master. Michel M',
 'Strom, Miss. Telma Matilda',
 'Asplund, Master. Edvin Rojj Felix',
 'Allison, Miss. Helen Loraine',
 'Allison, Master. Hudson Trevor',
 'Navratil, Master. Edmond Roger',
 'Coutts, Master. William Loch "William"',
 'Palsson, Miss. Stina Viola',
 'Nakid, Miss. Maria ("Mary")',
 'Goodwin, Master. Sidney Leonard',
 'Richards, Master. William Rowe',
 'Dodge, Master. Washington',
 'Baclini, Miss. Helene Barbara',
 'Hirvonen, Miss. Hildur E',
 'Quick, Miss. Phyllis May',
 'Becker, Miss. Marion Louise',
 'Skoog, Miss. Margit Elizabeth',
 'Baclini, Miss. Eugenie',
 'Karun, Miss. Manca',
 'Wells, Miss. Joan',
 'Hamalainen, Master. Viljo',
 'Dean, Master. Bertram Vere',
 'Thomas, Master. Assad Alexander',
 'Panula, Master. Urho Abraham',
 'Mallet, Master. Andre',
 'Richards, Master. George Sibley',
 'Andersson, Master. Sigvard Harald Elias',
 'Johnson, Master. Harold Theodor']

In [222]:
#Q. How many person are less tha 18 years old
len(df[df['Age']<18])

113

In [223]:
#Q. how many passengers have paid less than average fare
len(df[df["Fare"]<df['Fare'].mean()])

680

In [225]:
# How many passengers have paid 0 Fare
len(df[df["Fare"]==0])

15

In [227]:
list(df[df["Fare"]==0].Name)

['Leonard, Mr. Lionel',
 'Harrison, Mr. William',
 'Tornquist, Mr. William Henry',
 'Parkes, Mr. Francis "Frank"',
 'Johnson, Mr. William Cahoone Jr',
 'Cunningham, Mr. Alfred Fleming',
 'Campbell, Mr. William',
 'Frost, Mr. Anthony Wood "Archie"',
 'Johnson, Mr. Alfred',
 'Parr, Mr. William Henry Marsh',
 'Watson, Mr. Ennis Hastings',
 'Knight, Mr. Robert J',
 'Andrews, Mr. Thomas Jr',
 'Fry, Mr. Richard',
 'Reuchlin, Jonkheer. John George']

In [229]:
# how many passengers are male
df[df["Sex"]=="male"].shape[0]

577

In [231]:
df['Sex'].value_counts(normalize=True)*100

Sex
male      64.758698
female    35.241302
Name: proportion, dtype: float64

In [232]:
# How many passsengers are of class 1
df[df["Pclass"]==1].shape[0]

216

In [240]:
# how many female PAid more than avg fare?
df["Sex"][df["Fare"]>df['Fare'].mean()].value_counts() # my approach
df[(df["Sex"]=="female")&(df["Fare"]>df['Fare'].mean())].shape[0] # teacher approach

104

Class 03 Pandas Advance

In [1]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [2]:
#string slicing and now table slicing
df[0:100]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S

In [3]:
df[0:100:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.00,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.00,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.00,0,0,17463,51.8625,E46,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.00,0,2,347742,11.1333,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.00,0,0,A/5. 2151,8.0500,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.00,0,0,350406,7.8542,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.00,1,0,345763,18.0000,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.00,0,0,239865,26.0000,NaN,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.00,0,0,PC 17601,27.7208,NaN,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.00,1,0,PC 17604,82.1708,NaN,C
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.00,2,0,345764,18.0000,NaN,S
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.00,1,0,7546,9.4750,NaN,S
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
44,45,1,3,"Devaney, Miss. Margaret Delia",female,19.00,0,0,330958,7.8792,NaN,Q
46,47,0,3,"Lennon, Mr. Denis",male,NaN,1,0,370371,15.5000,NaN,Q
48,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
50,51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.00,1,0,PC 17572,76.7292,D33,C
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.00,0,1,113509,61.9792,B30,C
56,57,1,2,"Rugg, Miss. Emily",female,21.00,0,0,C.A. 31026,10.5000,NaN,S
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.00,0,0,2669,7.2292,NaN,C
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.00,1,0,36973,83.4750,C83,S
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C
66,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.00,0,0,C.A. 29395,10.5000,F33,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
70,71,0,2,"Jenkin, Mr. Stephen Curnow",male,32.00,0,0,C.A. 33111,10.5000,NaN,S
72,73,0,2,"Hood, Mr. Ambrose Jr",male,21.00,0,0,S.O.C. 14879,73.5000,NaN,S
74,75,1,3,"Bing, Mr. Lee",male,32.00,0,0,1601,56.4958,NaN,S
76,77,0,3,"Staneff, Mr. Ivan",male,NaN,0,0,349208,7.8958,NaN,S
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
80,81,0,3,"Waelens, Mr. Achille",male,22.00,0,0,345767,9.0000,NaN,S
82,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,NaN,Q
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
86,87,0,3,"Ford, Mr. William Neal",male,16.00,1,3,W./C. 6608,34.3750,NaN,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
90,91,0,3,"Christmann, Mr. Emil",male,29.00,0,0,343276,8.0500,NaN,S
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.00,1,0,W.E.P. 5734,61.1750,E31,S
94,95,0,3,"Coxon, Mr. Daniel",male,59.00,0,0,364500,7.2500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,34.6542,A5,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.00,0,1,231919,23.0000,NaN,S

In [ ]:
# ACCESS ROWS AND COLUNS OF A DATAFRMAE >> implicit/intgeer/internal indexing,exxplicitor anmed indexing

In [5]:
#implicit indexing
df.iloc[0:2]# start from 0 and go till 1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [6]:
#explicit indexing
df.loc[0:3]# start from 0 and go till 3
# loc is used fornamed indexes, iloc is used for integer indexes

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [8]:
# df.iloc[0:2,["Name","Sex"]] # this will throw an error because iloc used default integer indexs(the one which we use when there is header="None")
# so instead of using Name and Sex use intgere indexes
df.iloc[0:10,[1,2]]

   Survived  Pclass
0         0       3
1         1       1
2         1       3
3         1       1
4         0       3
5         0       3
6         0       1
7         0       3
8         1       3
9         1       2

In [9]:
# and for using named indexes we can use loc
df.loc[0:3,["Name","Sex"]]

                                                Name     Sex
0                            Braund, Mr. Owen Harris    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                             Heikkinen, Miss. Laina  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female

In [14]:
s1=pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [11]:
s=pd.Series(list(df['Name'][2:5]),index=['a','b','c'])
s

a                          Heikkinen, Miss. Laina
b    Futrelle, Mrs. Jacques Heath (Lily May Peel)
c                        Allen, Mr. William Henry
dtype: object

In [12]:
"PA"+"SKILLS"

'PASKILLS'

In [15]:
#Series with different indexes and dataframe can not be concatenated using "+" symbol
s+s1

a    NaN
b    NaN
c    NaN
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
dtype: object

In [16]:
# if you keep indexes same,then for series concatenation can happen
s1=pd.Series(list(df['Name'][5:8]),index =["a","b","c"])
s1

a                  Moran, Mr. James
b           McCarthy, Mr. Timothy J
c    Palsson, Master. Gosta Leonard
dtype: object

In [18]:
s+","+s1

a              Heikkinen, Miss. Laina,Moran, Mr. James
b    Futrelle, Mrs. Jacques Heath (Lily May Peel),M...
c    Allen, Mr. William Henry,Palsson, Master. Gost...
dtype: object

In [19]:
df.drop('PassengerId',axis=1)# drop/remove the passengerId column from the table

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [21]:
 df.drop('PassengerId',axis=1,inplace=True)# it will drop the PassengerID permanently from the df